name: Build and Push Docker Image to Harbor

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Harbor
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" | docker login ${{ secrets.HARBOR_URL }} -u ${{ secrets.HARBOR_USERNAME }} --password-stdin
      - name: Generate Date-Time-Based Tag
        id: generate_tag
        run: |
          new_version=$(date -u +"v%Y.%m.%d.%H%M%S")
          echo "Generated tag: $new_version"
          echo "version=$new_version" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.HARBOR_URL }}/${{ secrets.HARBOR_PROJECT }}/valko-webapp:latest
            ${{ secrets.HARBOR_URL }}/${{ secrets.HARBOR_PROJECT }}/valko-webapp:${{ env.version }}

      - name: Logout
        if: always()
        run: docker logout ${{ secrets.HARBOR_URL }}
